// GENERATED CODE - DO NOT MODIFY BY HAND
// Manual Hive TypeAdapter (normally generated by hive_generator)

part of 'paired_device.dart';

class PairedDeviceAdapter extends TypeAdapter<PairedDevice> {
  @override
  final int typeId = 0;

  @override
  PairedDevice read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{};
    for (int i = 0; i < numOfFields; i++) {
      fields[reader.readByte()] = reader.read();
    }
    return PairedDevice(
      id: fields[0] as String,
      name: fields[1] as String,
      ip: fields[2] as String,
      port: fields[3] as int,
      deviceToken: fields[4] as String,
      pairedAt: fields[5] as DateTime,
    );
  }

  @override
  void write(BinaryWriter writer, PairedDevice obj) {
    writer
      ..writeByte(6)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.name)
      ..writeByte(2)
      ..write(obj.ip)
      ..writeByte(3)
      ..write(obj.port)
      ..writeByte(4)
      ..write(obj.deviceToken)
      ..writeByte(5)
      ..write(obj.pairedAt);
  }

  @override
  int get hashCode => typeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PairedDeviceAdapter &&
          runtimeType == other.runtimeType &&
          typeId == other.typeId;
}
